apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: hello
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: hello
      annotations:
        flux.weave.works/automated: "true"
    spec:
      containers:
        - image: gcr.io/kuar-demo/kuard-amd64:1
          imagePullPolicy: Always
          name: hello-world-container
          ports:
            - containerPort: 8080
              name: web
---
apiVersion: v1
kind: Service
metadata:
  name: hello
spec:
  ports:
     -  port: 80
        name: http
        protocol: TCP
        targetPort: 8080
  selector:
    app: hello
